### ISSUE TITLE
should ECONNRESET error be ignored?

### ISSUE THREAD

**Issue by kiancyc** [dai-shi/easy-livereload#12]
I use easy-livereload with chrome LiveReload plugin, everytime page triggered refreshed with produced an error in express:

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read', stack: 'Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)', message: 'read ECONNRESET'}

**Comment by dai-shi** [comment]
Hi, I don't remember seeing such an error back then, so it's maybe new. Would you be willing to draft a PR for the fix?

**Comment by kiancyc** [comment]
#14 pull request created
