### ISSUE TITLE
EventEmitter deprecated

### ISSUE THREAD

**Issue by mariotacke** [dai-shi/easy-livereload#4]
This module does not seem to work with latest node (v8.4) since the `EventEmitter` was deprecated.

Error:
```
[...]\node_modules\websocket.io\lib\socket.js:49
Socket.prototype.__proto__ = EventEmitter.prototype;
                                         ^
                                         
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> ([...]\node_modules\websocket.io\lib\socket.js:49:42)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]\node_modules\websocket.io\lib\protocols\drafts.js:12:14)
    at Module._compile (module.js:573:30)
```

References
- https://github.com/LearnBoost/websocket.io/issues/55

**Comment by dai-shi** [comment]
Thanks for reporting.
This is still a workaround and may or may not work depending of package load order.
